//
// Created by a1807 on 2026/5/20.
//

#ifndef GCC_DEMO_BLE_COMMAND_H
#define GCC_DEMO_BLE_COMMAND_H

/* BLE+SPP通用指令 */
#define BLE_COMMAND_AT_TEST			"AT\r\n"
#define BLE_COMMAND_GET_BAUD		"AT+BAUD?\r\n"
#define BLE_COMMAND_SET_BAUD		"AT+BAUD=%lu,N\r\n"
#define BLE_COMMAND_SET_BAUD9600	"AT+BAUD=9600,N\r\n"
#define BLE_COMMAND_SET_BAUD115200	"AT+BAUD=115200,N\r\n"
#define BLE_COMMAND_SET_BAUD921600	"AT+BAUD=921600,N\r\n"
#define BLE_COMMAND_GET_VERSION		"AT+VERSION\r\n"
#define BLE_COMMAND_SET_LED_ON		"AT+LED=1\r\n"
#define BLE_COMMAND_SET_LED_OFF		"AT+LED=0\r\n"
#define BLE_COMMAND_GET_LED_STATUS	"AT+LED?\r\n"
#define BLE_COMMAND_SET_DEFAULT		"AT+DEFAULT\r\n"
#define BLE_COMMAND_RESET			"AT+RESET\r\n"
#define BLE_COMMAND_BTMODE_ON		"AT+BTMODE=1\r\n"
#define BLE_COMMAND_BTMODE_OFF		"AT+BTMODE=0\r\n"
#define BLE_COMMAND_GET_BTMODE		"AT+BTMODE?\r\n"
#define BLE_COMMAND_SET_ROLE_SLAVE	"AT+ROLE=S\r\n"
#define BLE_COMMAND_SET_ROLE_SPPMASTER	"AT+ROLE=M\r\n"
#define BLE_COMMAND_SET_ROLE_BLEMASTER	"AT+ROLE=BM\r\n"
#define BLE_COMMAND_GET_ROLE		"AT+ROLE?\r\n"
#define BLE_COMMAND_CLEAR			"AT+CLEAR\r\n"

/* SPP */
#define SPP_COMMAND_SET_NAME		"AT+NAME=MyBLEDevice\r\n"
#define SPP_COMMAND_GET_NAME		"AT+NAME?\r\n"
#define SPP_COMMAND_SET_PIN			"AT+PIN=1234\r\n"
#define SPP_COMMAND_GET_PIN			"AT+PIN?\r\n"
#define SPP_COMMAND_SET_ADDR		"AT+ADDR=2112220001\r\n"
#define SPP_COMMAND_GET_ADDR		"AT+ADDR?\r\n"
#define SPP_COMMAND_SET_COD			"AT+CLASS=100680\r\n"
#define SPP_COMMAND_GET_COD			"AT+CLASS?\r\n"

/* BLE */

#endif //GCC_DEMO_BLE_COMMAND_H
